// Run against a local HTTP server: NODE_PATH=/path/to/node_modules node tests/browser.cjs
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const base = process.env.BROWSER_URL || 'http://127.0.0.1:8123/';
(async () => {
  const browser = await chromium.launch({headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.addInitScript(()=>localStorage.setItem('rsi-language',JSON.stringify('zh')));
    await page.goto(base);
    await page.waitForSelector('.paper');
    const catalog=await (await page.request.get(base+'catalog/browser.json')).json();
    const total=catalog.works.length;
    assert.ok(total>=97);
    assert.equal(await page.locator('.paper').count(),total);
    assert.doesNotMatch(await page.locator('body').innerText(),/[\u4e00-\u9fff]/);
    for(const work of catalog.works){
      await page.locator(`[data-work="${work.slug}"]`).click();
      assert.doesNotMatch(await page.locator('#detail').innerText(),/[\u4e00-\u9fff]/,work.slug);
    }
    await page.locator('#research-insights').click();
    assert.equal(await page.locator('.insight [data-insight-work]').count(),catalog.insights.reduce((n,x)=>n+x.works.length,0));
    assert.doesNotMatch(await page.locator('#taxonomy-content').innerText(),/[\u4e00-\u9fff]/);
    await page.locator('[data-insight-work="intentlab-production"]').click();
    assert.match(await page.locator('#detail h2').textContent(),/IntentLab/);
    await page.locator('#about-taxonomy').click();
    assert.match(await page.locator('#taxonomy-content').textContent(),/not a quality ranking/);
    await page.locator('.dialog-close').click();
    await page.locator('[data-collection="papers"]').click();
    assert.equal(await page.locator('.paper').count(),catalog.works.filter(w=>w.source_type==='paper').length);
    await page.locator('[data-category="system"]').click();
    assert.ok(await page.locator('.paper').count()>0);
    await page.locator('#reset').click();
    await page.locator('[data-work="rise-policy-distillation"]').click();
    await page.locator('#detail [data-target="Model weights"]').click();
    assert.equal(await page.locator('.paper').count(),catalog.works.filter(w=>w.targets.includes('Model weights')).length);
    await page.locator('#reset').click();
    await page.locator('#search').fill('Qwen3-32B');
    assert.ok(await page.locator('.paper').count()>0);
    assert.ok(await page.locator('.paper').count()<total);
    await page.locator('#search').fill('no-such-work-xyz');
    assert.equal(await page.locator('.paper').count(),0);
    await page.locator('#empty-reset').click();
    await page.locator('[data-work="skysynth"]').click();
    assert.match(await page.locator('#detail h2').textContent(),/Sky/);
    await page.locator('#bookmark').click();
    await page.locator('[data-collection="saved"]').click();
    assert.equal(await page.locator('.paper').count(),1);
    await page.reload();
    await page.waitForSelector('.paper');
    assert.equal(await page.locator('.paper').count(),1);
    assert.match(await page.locator('#detail h2').textContent(),/Sky/);
    assert.equal(await page.locator('html').getAttribute('lang'),'en');
    assert.equal(await page.locator('#language').count(),0);
    await page.locator('#theme').click();
    assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
    await page.locator('#reset').click();
    await page.locator('#filter-toggle').click();
    await page.locator('#target').selectOption('Model weights');
    const weightWorks=catalog.works.filter(w=>w.targets.includes('Model weights'));
    assert.equal(await page.locator('.paper').count(),weightWorks.length);
    await page.reload();await page.waitForSelector('.paper');
    assert.equal(await page.locator('#target').inputValue(),'Model weights');
    assert.equal(await page.locator('.paper').count(),weightWorks.length);
    await page.locator('#reset').click();
    await page.locator('#filter-toggle').click();
    await page.locator('#year').selectOption('2026');
    await page.locator('#type').selectOption('project/blog');
    assert.ok(await page.locator('.paper').count()>0);
    await page.locator('#sort').selectOption('title');
    const titles=await page.locator('.paper-title').allTextContents();
    assert.deepEqual(titles,[...titles].sort((a,b)=>a.localeCompare(b)));
    const link=page.url();
    const fresh=await browser.newPage();
    await fresh.goto(link);await fresh.waitForSelector('.paper');
    assert.equal(await fresh.locator('.paper').count(),titles.length);
    assert.equal(await fresh.locator('#type').inputValue(),'project/blog');
    await page.locator('#reset').click();
    await page.keyboard.press('/');
    assert.equal(await page.evaluate(()=>document.activeElement.id),'search');
    await page.locator('#theme').click();
    await page.screenshot({path:'/tmp/rsi-browser-desktop.png'});
    const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
    mobile.on('pageerror',e=>errors.push(e.message));
    await mobile.goto(base);await mobile.waitForSelector('.paper');
    assert.equal(await mobile.locator('body').evaluate(el=>el.classList.contains('detail-open')),false);
    assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=390 && innerWidth===390));
    await mobile.screenshot({path:'/tmp/rsi-browser-mobile.png'});
    await mobile.locator('[data-work="vibeserve"]').click();
    await mobile.locator('#close-detail').waitFor({state:'visible'});
    assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=390 && innerWidth===390));
    await mobile.screenshot({path:'/tmp/rsi-browser-mobile-detail.png'});
    await mobile.locator('#close-detail').click();
    assert.equal(await mobile.locator('body').evaluate(el=>el.classList.contains('detail-open')),false);
    await mobile.goto(base+'?work=skysynth');await mobile.waitForSelector('#detail h2');
    assert.equal(await mobile.locator('body').evaluate(el=>el.classList.contains('detail-open')),true);
    // Loop profile: detail tags, facet filters, deep links and landscape cells all filter by the same catalog fields.
    const facetCount=(axis,value)=>catalog.works.filter(w=>(Array.isArray(w[axis])?w[axis]:[w[axis]]).includes(value)).length;
    await page.locator('#reset').click();
    await page.locator('[data-work="dgm"]').click();
    assert.equal(await page.locator('#detail .loop-profile dt').count(),6);
    await page.locator(`#detail [data-facet="loop"][data-value="${catalog.works.find(w=>w.slug==='dgm').loop}"]`).click();
    assert.equal(await page.locator('.paper').count(),facetCount('loop',catalog.works.find(w=>w.slug==='dgm').loop));
    assert.equal(await page.locator('#filters').isHidden(),false);
    await page.locator('#reset').click();
    await page.locator('#facet-evidence').selectOption('multi-round');
    await page.locator('#facet-feedback').selectOption('tests');
    const both=catalog.works.filter(w=>w.evidence.includes('multi-round')&&w.feedback.includes('tests')).length;
    assert.equal(await page.locator('.paper').count(),both);
    const facetLink=await browser.newPage();
    await facetLink.goto(base+'?persistence=memory&loop=self-harness');await facetLink.waitForSelector('#papers');
    assert.equal(await facetLink.locator('.paper').count(),catalog.works.filter(w=>w.persistence.includes('memory')&&w.loop==='self-harness').length);
    assert.equal(await facetLink.locator('#facet-loop').inputValue(),'self-harness');
    await page.locator('#reset').click();
    await page.locator('#landscape').click();
    assert.equal(await page.locator('.landscape-table').count(),6);
    const cell=page.locator('.landscape-table td button').first();
    const filter=JSON.parse(await cell.getAttribute('data-filter'));
    await cell.click();
    assert.equal(await page.locator('#taxonomy-dialog').evaluate(d=>d.open),false);
    const expected=catalog.works.filter(w=>Object.entries(filter).every(([axis,value])=>axis==='category'?w.category===value:(Array.isArray(w[axis])?w[axis]:[w[axis]]).includes(value))).length;
    assert.equal(await page.locator('.paper').count(),expected);
    await page.locator('#reset').click();
    await page.locator('#about-taxonomy').click();
    assert.equal(await page.locator('.axis-definition').count(),6);
    await page.locator('.dialog-close').click();
    const failed=await browser.newPage();
    await failed.route('**/catalog/browser.json',route=>route.fulfill({status:500,body:'unavailable'}));
    await failed.goto(base);await failed.getByText('The collection could not be loaded.').waitFor();
    assert.ok((await failed.locator('#papers a').getAttribute('href')).endsWith('README.md'));
    assert.deepEqual(errors,[]);
    console.log('PASS: catalog coverage; search, categories, compound filters, sorting, bookmarks, persistence, deep links, English-only persistence, target filters, loop-profile facets, landscape cells, theme, keyboard, mobile, load failure; no page errors.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
